import Head from 'next/head'
import Title from "../components/atoms/document/title";
import React from "react";
import LogoPrimary from "../public/img/logo_primary.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fancy ui kit</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
          <div className="noise"></div>
          <div className="login-main">
              <div className="left bg-noise">
                <div className="dbl-img">
                    <figure className="image-styled">
                        <img src="https://static01.nyt.com/images/2022/09/01/business/00roose-1/merlin_212276709_3104aef5-3dc4-4288-bb44-9e5624db0b37-superJumbo.jpg" alt=""/>
                    </figure>
                    <figure className="image-styled">
                        <img src="https://miro.medium.com/max/1400/1*XoVCoIeNJ16PYOmWKOs0mg.png" alt=""/>
                    </figure>
                </div>
                <Title level={"1"} className="white">Discover new <br/> creative worlds</Title>
                  <div className="dbl-img">
                      <figure className="image-styled">
                          <img src="https://i0.wp.com/grayarea.org/wp-content/uploads/2019/01/google-dream-starry-night.jpg?fit=1024%2C811&ssl=1" alt=""/>
                      </figure>
                      <figure className="image-styled">
                          <img src="https://assets.iflscience.com/assets/articleNo/65189/aImg/61687/ai-generated-art-meta.jpg" alt=""/>
                      </figure>
                  </div>
              </div>
              <div className="right">
                  <a href="">
                      <img src={LogoPrimary} alt="Logo Apertio"/>
                  </a>
              </div>
          </div>
      </main>
    </div>
  )
}
