import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fancy ui kit</title>
        <meta name="description" content="Generated by create next app" />
       
      </Head>
      <main>
        <h1>
          🚧 Documentation will be available soon 🚧
        </h1>
      </main>
    </div>
  )
}
